M48
; DRILL file {KiCad 8.0.5} date 2024-11-30T21:41:33+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-30T21:41:33+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X118.62Y-46.43
X118.62Y-52.21
T2
X91.347Y-59.09
T3
X83.5Y-29.5
X83.5Y-66.5
X120.5Y-29.5
X120.5Y-66.5
M30
